import "./globals.css";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import { AuthProvider } from "./auth/login";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DigiNest",
  description: "Generated by create DigiNest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
